#!/usr/bin/env python3
"""Base Clause Set Constructor (B_i) for Parallel Vampire Search.

Definitions:
- C₀ = Full clausified problem (Axioms ∪ negated_conjectures)
- C_ax = Axioms-only version (negated_conjectures removed from C₀)
- Variant = B_i + verified seeds + negated_conjectures

This module constructs BASE CLAUSE SETS ONLY (B_i ⊆ C_ax) from the axioms-only
version C_ax. It does NOT handle seed clause generation (S_i).

The complete variant construction is: Variant = B_i + S_i + negated_conjectures, where:
    - B_i ⊆ C_ax: Base clauses (selected by THIS module from axioms only)
    - S_i: Seed clauses (generated by seed_clause_set_constructor.py using LLM)
    - negated_conjectures: The negated conjectures to prove (from C₀)

This module provides multiple B_i selection strategies:
    - all: Use all axioms (B_i = C_ax)
    - random: Randomly sample a subset of axioms
    - priority: Keep unit clauses, sample others
    - stratified: Divide axioms into non-overlapping strata

Parses CNF (Clause Normal Form) and TFF (Typed First-order Form) clauses:
    - CNF format: cnf(name, role, clause). (from clausify mode)
    - TFF format: tff(name, role, (![X0 : $int] : (formula))). (from tclausify mode)
    - For TFF: Quantifiers are stripped to extract the clause content.

Uses tptp_parsing_utils for shared parsing logic (quantifier/parentheses handling).

IMPORTANT:
    - Input must be a clausified problem (CNF or TFF format). Use VampireClausifier first.
    - This module only constructs B_i, not complete variants C_i.
    - Seed clauses (S_i) are added separately by main.py after LLM generation.

Used by main.py to construct base clause sets for variants.

Usage:
    from base_clause_set_constructor import BaseClauseSetConstructor

    # Construct B_i (base clause set) from C_ax (axioms only)
    constructor = BaseClauseSetConstructor(logger, Path("problem_clausified_axioms.tptp"))
    base_clauses = constructor.construct_base_set(strategy="random", keep_ratio=0.7)

    # base_clauses is then combined with S_i and negated_conjectures by main.py
    # to form Variant = B_i + S_i + negated_conjectures
"""

import logging
import random
from pathlib import Path
from typing import List, Optional, Set, Tuple

from tptp_parsing_utils import (
    Clause,
    ClauseRole,
    parse_cnf_clause,
    parse_tff_clause,
    strip_quantifiers,
    strip_outer_parentheses,
)


class BaseClauseSelector:
    """Strategies for selecting base clauses B_i ⊆ C_ax.

    This class provides various strategies for selecting subsets of axioms
    from C_ax (axioms-only clause set) to create diverse starting points for
    parallel proof search.
    """

    @staticmethod
    def select_all(clauses: List[Clause]) -> List[Clause]:
        """Select all axioms (B_i = C_ax).

        Args:
            clauses: Axioms from C_ax.

        Returns:
            Copy of all input clauses.
        """
        return clauses.copy()

    @staticmethod
    def select_random(clauses: List[Clause], keep_ratio: float = 0.7) -> List[Clause]:
        """Randomly select a subset of axioms.

        Args:
            clauses: Axioms from C_ax.
            keep_ratio: Fraction of axioms to keep (0.0 to 1.0).

        Returns:
            Randomly sampled subset of axioms.
        """
        k = max(1, int(len(clauses) * keep_ratio))
        return random.sample(clauses, k)

    @staticmethod
    def select_by_role(
        clauses: List[Clause],
        keep_roles: Set[ClauseRole],
        keep_all_conjectures: bool = True,
    ) -> List[Clause]:
        """Select clauses based on their TPTP role.

        Args:
            clauses: Original clause set.
            keep_roles: Set of roles to keep.
            keep_all_conjectures: Always keep negated conjectures (recommended).

        Returns:
            Clauses matching the specified roles.
        """
        selected = []
        for clause in clauses:
            if keep_all_conjectures and clause.role == ClauseRole.NEGATED_CONJECTURE:
                selected.append(clause)
            elif clause.role in keep_roles:
                selected.append(clause)
        return selected

    @staticmethod
    def select_priority(
        clauses: List[Clause],
        keep_conjectures: bool = True,
        keep_units: bool = True,
        keep_ratio: float = 0.8,
    ) -> List[Clause]:
        """Priority-based selection: keep important clauses, sample others.

        Note: keep_conjectures parameter is ignored when operating on C_ax
        since C_ax has no negated_conjectures.

        Args:
            clauses: Axioms from C_ax.
            keep_conjectures: (Ignored - C_ax has no conjectures).
            keep_units: Always keep unit clauses.
            keep_ratio: Ratio of remaining clauses to keep.

        Returns:
            Priority clauses plus sampled regular clauses.
        """
        priority = []
        regular = []

        for clause in clauses:
            # Check if it's a priority clause
            is_conjecture = clause.role == ClauseRole.NEGATED_CONJECTURE
            # Simple heuristic: unit clauses typically have fewer characters
            is_unit = len(clause.literals) < 50 and clause.literals.count("|") == 0

            if (keep_conjectures and is_conjecture) or (keep_units and is_unit):
                priority.append(clause)
            else:
                regular.append(clause)

        # Keep all priority clauses and sample from regular ones
        k = max(0, int(len(regular) * keep_ratio))
        sampled = random.sample(regular, k) if regular else []

        return priority + sampled

    @staticmethod
    def select_stratified(
        clauses: List[Clause], num_strata: int = 3, stratum_idx: int = 0
    ) -> List[Clause]:
        """Divide axioms into strata and select one stratum.

        Useful for creating diverse variants. When operating on C_ax, all clauses
        are axioms (no negated_conjectures).

        Args:
            clauses: Axioms from C_ax.
            num_strata: Number of strata to divide into.
            stratum_idx: Which stratum to select (0 to num_strata-1).

        Returns:
            One stratum of axiom clauses.
        """
        # When operating on C_ax, all clauses are axioms
        # (negated_conjectures are in C₀, not C_ax)
        conjectures = [c for c in clauses if c.role == ClauseRole.NEGATED_CONJECTURE]
        other_clauses = [c for c in clauses if c.role != ClauseRole.NEGATED_CONJECTURE]

        # Shuffle and divide
        random.shuffle(other_clauses)
        stratum_size = len(other_clauses) // num_strata
        start_idx = stratum_idx * stratum_size
        end_idx = (
            start_idx + stratum_size
            if stratum_idx < num_strata - 1
            else len(other_clauses)
        )

        return conjectures + other_clauses[start_idx:end_idx]


class BaseClauseSetConstructor:
    """Constructs base clause sets B_i from C_ax (axioms only).

    This class parses CNF and TFF clausified problems from Vampire's clausify/tclausify modes
    and provides methods to construct base clause sets B_i using various
    selection strategies.

    Typically operates on C_ax (axioms-only file with negated_conjectures removed),
    but can also parse C₀ (full clausified problem) when needed.

    Supports both formats:
    - CNF format: cnf(name, role, clause). (from clausify mode)
    - TFF format: tff(name, role, (![X : $int] : (formula))). (from tclausify mode)
    For TFF: Quantifiers are stripped to extract the clause content for processing.

    IMPORTANT: This class ONLY constructs B_i (base clauses), not S_i (seed clauses).
    Seed clauses are generated separately by seed_clause_set_constructor.py using LLM.
    The complete variant (B_i + S_i + negated_conjectures) is assembled by main.py.
    """

    def __init__(self, logger: logging.Logger, clausified_problem: Path):
        """Initialize constructor with a clausified problem.

        Args:
            logger: Logger instance for logging.
            clausified_problem: Path to clausified problem file (CNF or TFF format).
                Typically C_ax (axioms only), but can also be C₀ (full problem).
                Use VampireClausifier (clausify or tclausify mode) to convert problems first.
        """
        self.logger = logger
        self.problem_path = Path(clausified_problem)
        self.clauses: List[Clause] = []
        self.header_lines: List[str] = []  # Comments, type declarations, etc.

        self._parse_problem()

    def _parse_problem(self) -> None:
        """Parse the clausified TPTP problem."""
        if not self.problem_path.exists():
            raise FileNotFoundError(f"Problem file not found: {self.problem_path}")

        with open(self.problem_path, "r") as f:
            lines = f.readlines()

        i = 0
        while i < len(lines):
            line = lines[i].strip()

            # Skip empty lines
            if not line:
                i += 1
                continue

            # Store header/comment lines
            if line.startswith("%"):
                self.header_lines.append(line)
                i += 1
                continue

            # Parse TFF or CNF clause (may span multiple lines)
            if line.startswith("tff("):
                full_clause, lines_consumed = self._read_full_clause(lines, i)
                clause = parse_tff_clause(full_clause, self.logger)
                if clause:
                    self.clauses.append(clause)
                i += lines_consumed
            elif line.startswith("cnf("):
                full_clause, lines_consumed = self._read_full_clause(lines, i)
                clause = parse_cnf_clause(full_clause, self.logger)
                if clause:
                    self.clauses.append(clause)
                i += lines_consumed
            else:
                i += 1

    def _read_full_clause(self, lines: List[str], start_idx: int) -> Tuple[str, int]:
        """Read a complete clause that may span multiple lines.

        Args:
            lines: All lines from the file.
            start_idx: Index to start reading from.

        Returns:
            Tuple of (full_clause_text, number_of_lines_consumed).
        """
        clause_lines = []
        i = start_idx

        while i < len(lines):
            line = lines[i].strip()
            clause_lines.append(line)

            # Check if we've reached the end of the clause
            if line.endswith(")."):
                break
            i += 1

        # Join lines with a space
        full_clause = " ".join(clause_lines)
        lines_consumed = i - start_idx + 1

        return full_clause, lines_consumed

    def construct_base_set(self, strategy: str = "all", **kwargs) -> List[Clause]:
        """Construct base clause set B_i using specified strategy.

        Args:
            strategy: Selection strategy - "all", "random", "by_role",
                "priority", or "stratified".
            **kwargs: Strategy-specific parameters (see BaseClauseSelector methods).

        Returns:
            Selected base clauses B_i.

        Raises:
            ValueError: If strategy name is not recognized.
        """
        if strategy == "all":
            return BaseClauseSelector.select_all(self.clauses)
        elif strategy == "random":
            return BaseClauseSelector.select_random(
                self.clauses, keep_ratio=kwargs.get("keep_ratio", 0.7)
            )
        elif strategy == "by_role":
            return BaseClauseSelector.select_by_role(
                self.clauses,
                keep_roles=kwargs.get("keep_roles", {ClauseRole.AXIOM}),
                keep_all_conjectures=kwargs.get("keep_all_conjectures", True),
            )
        elif strategy == "priority":
            return BaseClauseSelector.select_priority(
                self.clauses,
                keep_conjectures=kwargs.get("keep_conjectures", True),
                keep_units=kwargs.get("keep_units", True),
                keep_ratio=kwargs.get("keep_ratio", 0.8),
            )
        elif strategy == "stratified":
            return BaseClauseSelector.select_stratified(
                self.clauses,
                num_strata=kwargs.get("num_strata", 3),
                stratum_idx=kwargs.get("stratum_idx", 0),
            )
        else:
            raise ValueError(f"Unknown strategy: {strategy}")

    def get_statistics(self) -> dict:
        """Get statistics about the original clause set.

        Returns:
            Dictionary containing total_clauses, role_distribution, and problem_path.
        """
        role_counts = {}
        for clause in self.clauses:
            role_counts[clause.role.value] = role_counts.get(clause.role.value, 0) + 1

        return {
            "total_clauses": len(self.clauses),
            "role_distribution": role_counts,
            "problem_path": str(self.problem_path),
        }


if __name__ == "__main__":
    """Test TPTP clause parsing logic (CNF and TFF)."""
    import sys
    import tempfile

    # Set up a basic logger
    logging.basicConfig(level=logging.WARNING)
    logger = logging.getLogger()

    # Import parsing functions for testing
    from tptp_parsing_utils import parse_tff_clause

    print("Testing TPTP clause parsing (CNF and TFF):\n")
    print("=" * 80)

    constructor = BaseClauseSetConstructor.__new__(BaseClauseSetConstructor)
    constructor.logger = logger

    # Test 1: TFF clause parsing
    print("\n1. Testing TFF clause parsing:")
    print("-" * 80)

    tff_tests = [
        "tff(u10,axiom, (![X0] : ((mult(e,X0) = X0)))).",
        "tff(u11,axiom, (![X0 : $int] : (($uminus($uminus(X0)) = X0)))).",
        "tff(u12,axiom, (![X0 : $int, X1 : $int] : (($less(X0,X1) | $less(X1,$sum(X0,1)))))).",
        "tff(u14,negated_conjecture, (mult(sK0,sK1) != mult(sK1,sK0))).",
    ]

    tff_passed = True
    for tff_clause in tff_tests:
        clause = parse_tff_clause(tff_clause, logger)
        if clause:
            print(f"  ✓ Parsed: {tff_clause}")
            print(f"    Name:     {clause.name}")
            print(f"    Role:     {clause.role.value}")
            print(f"    Literals: {clause.literals}")
        else:
            print(f"  ✗ FAILED to parse: {tff_clause}")
            tff_passed = False
        print()

    # Test 2: Full workflow with TFF file
    print("\n2. Testing full workflow with TFF file:")
    print("-" * 80)

    tff_content = """% Test TFF file
tff(t1,axiom, (![X0] : ((q(X0) | r(X0))))).
tff(t2,axiom, (![X0 : $int] : (($less(X0,$sum(X0,1)))))).
tff(t3,negated_conjecture, (mult(sK0,sK1) != mult(sK1,sK0))).
"""

    with tempfile.NamedTemporaryFile(mode="w", suffix=".tptp", delete=False) as tmp:
        tmp.write(tff_content)
        tmp_path = Path(tmp.name)

    try:
        test_constructor = BaseClauseSetConstructor(logger, tmp_path)
        stats = test_constructor.get_statistics()

        print(f"  ✓ Successfully parsed TFF file")
        print(f"    Total clauses: {stats['total_clauses']}")
        print(f"    Expected: 3 clauses")

        if stats["total_clauses"] == 3:
            print(f"    ✓ Correct number of clauses")
            workflow_passed = True
        else:
            print(f"    ✗ Wrong number of clauses")
            workflow_passed = False

        print("\n    Parsed clauses:")
        for clause in test_constructor.clauses:
            print(
                f"      - {clause.name} ({clause.role.value}): {clause.literals[:50]}..."
            )
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        workflow_passed = False
    finally:
        tmp_path.unlink()

    # Summary
    print("\n" + "=" * 80)
    print("Test Summary:")
    print("-" * 80)

    all_passed = tff_passed and workflow_passed

    tests = [
        ("TPTP clause parsing (TFF)", tff_passed),
        ("TPTP file workflow", workflow_passed),
    ]

    for test_name, passed in tests:
        status = "✓ PASS" if passed else "✗ FAIL"
        print(f"  {status}: {test_name}")

    print()
    if all_passed:
        print("✓ All test cases passed")
        sys.exit(0)
    else:
        print("✗ Some test cases failed")
        sys.exit(1)
