#!/usr/bin/env python3
"""Entailment Checker for Parallel Vampire Search.

This module verifies that seed clauses S_i are entailed by the original
clausified problem C₀ using Vampire's native conjecture proving.

The entailment checking workflow:
1. Take a seed clause s (generated by seed_clause_set_constructor.py)
2. Convert all negated_conjecture clauses in C₀ to hypothesis role
3. Add seed clause s with conjecture role
4. Run Vampire to prove the conjecture
5. Return verification result:
   - UNSAT/Refutation: s is entailed by C₀ (safe to use in variants)
   - SAT or UNKNOWN: s is not entailed (reject seed)

This approach leverages Vampire's native conjecture handling instead of manual
clause negation. Vampire internally negates the conjecture and tries to derive
a contradiction from C₀ ∪ {¬s}.

This ensures soundness of the parallel search: if any variant C_i = B_i ∪ S_i
is UNSAT, then the original problem C₀ is UNSAT, since all s ∈ S_i satisfy C₀ ⊨ s.

IMPORTANT:
    - This module only verifies entailment, it does not generate or construct clauses.
    - Base clauses (B_i) are constructed by base_clause_set_constructor.py.
    - Seed clauses (S_i) are generated by seed_clause_set_constructor.py.
    - This module validates seeds before they are added to variants by main.py.

Used by main.py to validate seed clauses before adding them to variants.

Usage:
    from entailment_checker import EntailmentChecker

    checker = EntailmentChecker(
        logger,
        vampire_binary="../build/vampire",
        timeout=10
    )

    is_entailed = checker.check_entailment(
        clausified_problem_path,
        seed_clause
    )

    # Only add seed to variant if is_entailed is True
"""

import logging
import re
import subprocess
import tempfile
from pathlib import Path


class EntailmentChecker:
    """Verify entailment of seed clauses using Vampire's native conjecture proving.

    This class implements entailment checking by:
    1. Converting C₀'s negated_conjecture clauses to hypothesis role
    2. Adding the seed clause s with conjecture role
    3. Running Vampire to prove s from the modified C₀

    If Vampire proves the conjecture (UNSAT), then C₀ ⊨ s.

    This approach is cleaner than manual negation and leverages Vampire's
    native conjecture handling mechanism.

    IMPORTANT: This checker assumes TFF clausified input from tclausify mode.
    Use VampireClausifier first if needed.
    """

    def __init__(
        self,
        logger: logging.Logger,
        vampire_binary: str = "../build/vampire",
        timeout: int = 10,
    ):
        """Initialize the entailment checker.

        Args:
            logger: Logger instance for logging.
            vampire_binary: Path to vampire executable.
            timeout: Timeout in seconds for entailment checks (default: 10).
        """
        self.logger = logger
        self.vampire_binary = vampire_binary
        self.timeout = timeout

    def check_entailment(
        self,
        clausified_problem: Path,
        seed_clause: str,
    ) -> bool:
        """Check if a seed clause is entailed by the original problem.

        Verifies C₀ ⊨ s by:
        1. Converting all negated_conjecture clauses in C₀ to hypothesis role
           (handles multi-line clauses by reading entire file)
        2. Adding seed clause s with conjecture role (using regex to replace role)
        3. Running Vampire to prove the conjecture

        Args:
            clausified_problem: Path to clausified problem file (C₀).
            seed_clause: Seed clause in TFF format to check.

        Returns:
            True if clause is entailed (Vampire proves it), False otherwise.
        """
        try:
            self.logger.debug(f"  Checking entailment for seed: {seed_clause}")

            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".tptp", delete=False
            ) as tmp:
                tmp_path = Path(tmp.name)

                # Read C₀ and convert negated_conjecture → hypothesis
                # Read entire file first to handle multi-line clauses
                with open(clausified_problem, "r") as f:
                    content = f.read()

                # Replace all occurrences of negated_conjecture with hypothesis
                content = content.replace("negated_conjecture", "hypothesis")

                tmp.write(content)

                # Add seed clause with conjecture role
                # Replace the role (second field) with 'conjecture' using regex
                if seed_clause.startswith("tff("):
                    # Pattern: tff(name, role, formula) -> tff(name, conjecture, formula)
                    # Captures: tff(name,) ROLE (,rest)
                    seed_with_conjecture = re.sub(
                        r"(tff\([^,]+,)\s*(axiom|hypothesis|lemma|negated_conjecture)\s*(,)",
                        r"\1 conjecture\3",
                        seed_clause,
                    )
                    tmp.write(f"\n{seed_with_conjecture}\n")
                else:
                    self.logger.warning(
                        f"  Seed clause not in TFF format: {seed_clause}"
                    )
                    return False

            # Log the temporary file
            self.logger.debug(f"  Created temporary file: {tmp_path}")
            self.logger.debug(f"  Temporary file contents:")
            with open(tmp_path, "r") as f:
                for line_num, line in enumerate(f, 1):
                    if line.strip():
                        self.logger.debug(f"    {line_num:3d}: {line.rstrip()}")

            # Run Vampire to prove the conjecture
            result = self._run_vampire(tmp_path)

            # Clean up temporary file
            try:
                tmp_path.unlink()
            except Exception as cleanup_error:
                self.logger.debug(
                    f"  Failed to clean up temp file {tmp_path}: {cleanup_error}"
                )

            return result == "unsat"

        except Exception as e:
            self.logger.error(f"  Entailment check failed: {e}", exc_info=True)
            return False

    def _run_vampire(self, problem_file: Path) -> str:
        """Run Vampire on a problem and return the result.

        Executes Vampire with default mode and the configured timeout to
        determine if the conjecture is proved.

        Args:
            problem_file: Path to TPTP problem file with hypothesis clauses
                         and a conjecture to prove.

        Returns:
            Result classification:
            - "unsat": Refutation found (conjecture is proved, seed is entailed)
            - "sat": Model found (conjecture is not proved)
            - "unknown": Timeout, error, or indeterminate result
        """
        try:
            cmd = [
                self.vampire_binary,
                str(problem_file),
            ]

            self.logger.debug(f"  Running Vampire: {' '.join(cmd)}")

            result = subprocess.run(
                cmd + ["--mode", "casc"],
                capture_output=True,
                text=True,
                timeout=self.timeout,
            )

            output = result.stdout + result.stderr

            # Log non-zero exit codes
            if result.returncode != 0:
                self.logger.debug(f"  Vampire exit code: {result.returncode}")
                if result.stderr:
                    # Indent each line of stderr for readability
                    stderr_lines = result.stderr[:500].split("\n")
                    self.logger.debug(f"  Vampire stderr:")
                    for line in stderr_lines:
                        if line.strip():
                            self.logger.debug(f"    {line}")

            # Check for refutation (UNSAT)
            if "Refutation found" in output or "% SZS status Unsatisfiable" in output:
                self.logger.debug("  Entailment check result: UNSAT (entailed)")
                return "unsat"
            elif "% SZS status Satisfiable" in output:
                self.logger.debug("  Entailment check result: SAT (not entailed)")
                return "sat"
            else:
                self.logger.debug(f"  Entailment check result: UNKNOWN")
                if output:
                    # Indent each line of output for readability
                    # output_lines = output[:500].split("\n")
                    output_lines = output.split("\n")
                    self.logger.debug(f"  Vampire output (first 500 chars):")
                    for line in output_lines:
                        if line.strip():
                            self.logger.debug(f"    {line}")
                return "unknown"

        except subprocess.TimeoutExpired:
            self.logger.debug(
                f"  Entailment check timeout after {self.timeout}s (treated as unknown)"
            )
            return "unknown"
        except Exception as e:
            self.logger.error(f"  Vampire execution failed: {e}", exc_info=True)
            return "unknown"


if __name__ == "__main__":
    """Test role conversion and entailment checking setup."""
    import sys

    print("Testing EntailmentChecker role conversion:")
    print()
    print("=" * 80)

    # Test 1: Role conversion (negated_conjecture → hypothesis)
    print("\n1. Testing role conversion logic:")
    print("-" * 80)

    test_lines = [
        "tff(c1, axiom, p(X)).",
        "tff(c2, negated_conjecture, ~q(Y)).",
        "tff(c3, hypothesis, r(Z)).",
        "tff(c4, negated_conjecture, (mult(a,b) != mult(b,a))).",
    ]

    expected_output = [
        "tff(c1, axiom, p(X)).",
        "tff(c2, hypothesis, ~q(Y)).",
        "tff(c3, hypothesis, r(Z)).",
        "tff(c4, hypothesis, (mult(a,b) != mult(b,a))).",
    ]

    conversion_passed = True
    for i, line in enumerate(test_lines):
        converted = line.replace(", negated_conjecture,", ", hypothesis,")
        expected = expected_output[i]
        status = "✓" if converted == expected else "✗"
        if converted != expected:
            conversion_passed = False
        print(f"  {status} Input:    {line}")
        print(f"    Expected: {expected}")
        print(f"    Got:      {converted}")
        print()

    # Test 2: Seed clause role conversion
    print("\n2. Testing seed clause role conversion to conjecture:")
    print("-" * 80)

    seed_tests = [
        "tff(seed1, axiom, p(a)).",
        "tff(seed2, lemma, (![X : $int] : ($less(X, $sum(X, 1))))).",
        "tff(seed3, hypothesis, mult(e, X) = X).",
    ]

    seed_expected = [
        "tff(seed1, conjecture, p(a)).",
        "tff(seed2, conjecture, (![X : $int] : ($less(X, $sum(X, 1))))).",
        "tff(seed3, conjecture, mult(e, X) = X).",
    ]

    seed_passed = True
    for i, seed in enumerate(seed_tests):
        converted = (
            seed.replace(", axiom,", ", conjecture,")
            .replace(", lemma,", ", conjecture,")
            .replace(", hypothesis,", ", conjecture,")
        )
        expected = seed_expected[i]
        status = "✓" if converted == expected else "✗"
        if converted != expected:
            seed_passed = False
        print(f"  {status} Seed:     {seed}")
        print(f"    Expected: {expected}")
        print(f"    Got:      {converted}")
        print()

    # Summary
    print("\n" + "=" * 80)
    print("Test Summary:")
    print("-" * 80)

    all_passed = conversion_passed and seed_passed

    tests = [
        ("Role conversion (negated_conjecture → hypothesis)", conversion_passed),
        ("Seed clause role conversion (→ conjecture)", seed_passed),
    ]

    for test_name, passed in tests:
        status = "✓ PASS" if passed else "✗ FAIL"
        print(f"  {status}: {test_name}")

    print()
    if all_passed:
        print("✓ All test cases passed")
        sys.exit(0)
    else:
        print("✗ Some test cases failed")
        sys.exit(1)
