#!/usr/bin/env python3
"""Seed Clause Set Constructor (S_i) for Parallel Vampire Search.

Definitions:
- C₀ = Full clausified problem (Axioms ∪ negated_conjectures)
- C_ax = Axioms-only version (negated_conjectures removed from C₀)
- Variant = B_i + verified seeds + negated_conjectures

This module constructs SEED CLAUSE SETS ONLY (S_i) using LLM prompting.
It does NOT handle base clause selection (B_i).

The complete variant construction is: Variant = B_i + S_i + negated_conjectures, where:
    - B_i: Base clauses (selected by base_clause_set_constructor.py from C_ax)
    - S_i: Seed clauses (generated by THIS module using LLM)
    - negated_conjectures: The negated conjectures to prove (from C₀)

This module handles communication with OpenAI to generate seed clause
suggestions. Generated clauses are suggestions only and must be validated
for entailment (C_ax ⊨ s) by Vampire before use.

The workflow is:
1. Extract problem context (comments from original problem, sample clauses from C_ax)
2. Prompt LLM to suggest helpful lemmas that follow from the axioms
3. Parse structured response (using function calling schema) to extract TPTP TFF clauses
4. Validate each suggestion using entailment checking (via entailment_checker.py)

The module uses OpenAI function calling with a defined schema to ensure
structured, parseable responses from the LLM. Generated clauses use TFF
(Typed First-order Form) format to preserve type information.

IMPORTANT:
    - This module only generates S_i (seed clauses), not complete variants.
    - Base clauses (B_i) are constructed by base_clause_set_constructor.py from C_ax.
    - Seeds are verified using entailment_checker.py (C_ax ⊨ s, --check-entailment flag).
    - The complete variant (B_i + S_i + negated_conjectures) is assembled by main.py.

Used by main.py to generate seed clauses for variants.

Usage:
    from seed_clause_set_constructor import SeedClauseGenerator

    generator = SeedClauseGenerator(logger, model="o4-mini")
    seeds = generator.generate_seeds(context, base_clauses, num_seeds=5)

    # seeds are then combined with B_i and negated_conjectures by main.py
    # to form Variant = B_i + S_i + negated_conjectures

Requires:
    - openai package (v1.0+): pip install openai>=1.0.0
    - OPENAI_API_KEY environment variable
"""

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from openai import OpenAI


@dataclass
class SeedClause:
    """A suggested seed clause from the LLM.

    Attributes:
        content: The clause in TPTP format.
        description: LLM's explanation of the clause.
        confidence: Optional confidence score (default: 1.0).
    """

    content: str
    description: str
    confidence: float = 1.0


class SeedClauseGenerator:
    """Generate seed clause suggestions using OpenAI for S_i construction.

    This generator creates prompts for the LLM based on problem context
    and parses the responses to extract TPTP clause suggestions.

    Generated clauses are unverified suggestions that require entailment
    checking before being added to variants.
    """

    # Schema for structured LLM output using OpenAI function calling
    # Expected response format:
    # {
    #   "seed_clauses": [
    #     {
    #       "clause": "tff(lemma1, axiom, ![X: $int]: mult(e, X) = X).",
    #       "explanation": "Identity element property",
    #       "confidence": 0.95
    #     },
    #     ...
    #   ]
    # }
    SEED_CLAUSES_SCHEMA = {
        "name": "generate_seed_clauses",
        "description": "Generate helpful seed clauses for a theorem proving problem",
        "parameters": {
            "type": "object",
            "properties": {
                "seed_clauses": {
                    "type": "array",
                    "description": "List of suggested seed clauses",
                    "items": {
                        "type": "object",
                        "properties": {
                            "clause": {
                                "type": "string",
                                "description": "The clause in TPTP TFF format (e.g., 'tff(lemma1, axiom, ![X: $int]: p(X)).')",
                            },
                            "explanation": {
                                "type": "string",
                                "description": "Brief explanation of why this clause is useful",
                            },
                            "confidence": {
                                "type": "number",
                                "description": "Confidence score between 0 and 1",
                                "minimum": 0,
                                "maximum": 1,
                            },
                        },
                        "required": ["clause", "explanation"],
                    },
                }
            },
            "required": ["seed_clauses"],
        },
    }

    def __init__(
        self,
        logger: logging.Logger,
        api_key: Optional[str] = None,
        model: str = "o4-mini",
    ):
        """Initialize the seed clause generator.

        Args:
            logger: Logger instance for logging.
            api_key: OpenAI API key (defaults to OPENAI_API_KEY env var).
            model: OpenAI model to use (default: o4-mini).

        Raises:
            ValueError: If no API key is provided or found in environment.
        """
        self.logger = logger
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "OpenAI API key required. Set OPENAI_API_KEY env var or pass api_key."
            )

        self.client = OpenAI(api_key=self.api_key)
        self.model = model

    def generate_seeds(
        self,
        problem_context: str,
        base_clauses: List[str],
        num_seeds: int = 5,
        domain_hint: Optional[str] = None,
    ) -> List[SeedClause]:
        """Generate seed clause suggestions for a problem.

        Args:
            problem_context: Problem description or header comments.
            base_clauses: Sample of base clauses B_i for context.
            num_seeds: Number of seed clauses to generate.
            domain_hint: Optional domain hint (e.g., "group theory", "arithmetic").

        Returns:
            List of suggested seed clauses (unverified).
        """
        self.logger.info(f"  Requesting {num_seeds} seed clauses from {self.model}")

        prompt = self._build_prompt(
            problem_context, base_clauses, num_seeds, domain_hint
        )

        # Log the full prompt being sent
        self.logger.info("")
        self.logger.info("  >>> LLM PROMPT START >>>")
        self.logger.info(prompt)
        self.logger.info("  <<< LLM PROMPT END <<<")
        self.logger.info("")

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are an expert in automated theorem proving and first-order logic. "
                            "Your task is to suggest helpful lemmas and intermediate clauses that are "
                            "logical consequences of the given axioms. Provide clauses in TPTP TFF format with type quantifiers."
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                functions=[self.SEED_CLAUSES_SCHEMA],
                function_call={"name": "generate_seed_clauses"},
            )

            # Log the full LLM response
            self.logger.info("")
            self.logger.info("  >>> LLM RESPONSE START >>>")
            self.logger.info(response.model_dump_json(indent=2))
            self.logger.info("  <<< LLM RESPONSE END <<<")
            self.logger.info("")

            message = response.choices[0].message
            function_args = json.loads(message.function_call.arguments)
            seeds = self._parse_schema_response(function_args)

            self.logger.info(f"  Generated {len(seeds)} seed clause suggestions")
            return seeds

        except Exception as e:
            self.logger.error(f"  LLM generation failed: {e}")
            return []

    def _build_prompt(
        self,
        problem_context: str,
        base_clauses: List[str],
        num_seeds: int,
        domain_hint: Optional[str] = None,
    ) -> str:
        """Build the prompt for seed clause generation.

        Args:
            problem_context: Problem description or header comments.
            base_clauses: Sample of base clauses for context.
            num_seeds: Number of seed clauses to request.
            domain_hint: Optional domain hint (e.g., "group theory").

        Returns:
            Formatted prompt string for the LLM.
        """
        domain_line = f"\nDomain: {domain_hint}\n" if domain_hint else ""

        clauses_sample = "\n".join(base_clauses)

        prompt = f"""
I need help generating useful lemmas for a theorem proving problem.

## Problem Context
{problem_context}
{domain_line}

## Sample Clauses
{clauses_sample}

## Task
Generate {num_seeds} lemmas or intermediate clauses that are logical consequences of the given axioms. These lemmas should capture interesting properties, relationships, or simplifications.

## Requirements

**Content Quality:**
- Focus on general lemmas that follow from the existing axioms
- Prioritize general properties, symmetries, or transitivity rules relevant to the domain
- Consider lemmas that simplify complex expressions or establish useful equivalences
- Ensure logical consistency with the given clauses

**Format Specifications:**
- Use TPTP TFF (Typed First-order Form) syntax: `tff(name, role, formula).`
- Role should be `axiom` for general principles or `lemma` for derived facts
- Include explicit type quantifiers (e.g., `![X: $int]: ...` for integers)
- Prefer simple forms: unit clauses or binary clauses when possible
- Use descriptive names that indicate the lemma's purpose
- Note: User-defined predicates/functions have no `$` prefix; built-in TPTP symbols like `$int`, `$real` do

## Output Format
For each lemma, provide:
1. The TFF clause
2. A brief 1-sentence explanation of why this lemma could be useful

## Example

tff(transitivity_leq, axiom, ![X: $int, Y: $int, Z: $int]: ((leq(X, Y) & leq(Y, Z)) => leq(X, Z))).

Explanation: Establishes transitivity of the user-defined leq (less-than-or-equal) predicate, enabling chaining of inequalities.

---

Please generate the {num_seeds} lemmas now.
"""
        return prompt

    def _parse_schema_response(self, function_args: Dict[str, Any]) -> List[SeedClause]:
        """Parse structured schema response from function call.

        Args:
            function_args: Parsed JSON arguments from function call.

        Returns:
            List of seed clauses.
        """
        seeds = []
        seed_clauses_data = function_args.get("seed_clauses", [])

        for seed_data in seed_clauses_data:
            clause = seed_data.get("clause", "").strip()
            explanation = seed_data.get("explanation", "").strip()
            confidence = seed_data.get("confidence", 1.0)

            if clause:
                seeds.append(
                    SeedClause(
                        content=clause,
                        description=explanation,
                        confidence=confidence,
                    )
                )

        return seeds

    def extract_problem_context(self, problem_file: Path) -> str:
        """Extract problem context from TPTP file.

        Extracts only header comments (metadata, domain info, etc.).
        Deliberately excludes conjecture to avoid biasing seed generation.

        Args:
            problem_file: Path to TPTP problem file.

        Returns:
            Extracted context string (header comments only).
        """
        context_lines = []
        with open(problem_file, "r") as f:
            for line in f:
                line = line.strip()
                # Include comments only
                if line.startswith("%"):
                    context_lines.append(line)
                # Stop at first non-comment line
                elif context_lines and not line.startswith("%") and line:
                    break

        return "\n".join(context_lines) if context_lines else "No context available"
